---
- name: Deploy application
  hosts: webservers
  become: true

  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/webservers.yml
    - ../../group_vars/all/vault.yml

  vars:
    application_source: "{{ playbook_dir }}/../../docker-project/"

  roles:
    - docker
    - app

