[webservers]
web01 ansible_host=172.31.38.105
web02 ansible_host=172.31.46.86
web03 ansible_host=172.31.23.144



[databases]
db01 ansible_host=172.31.38.250

[monitoring]
monitoring01 ansible_host=172.31.36.176

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/ansible_ed25519
