---
- name: Install MySQL
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: true

- name: Start MySQL
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create application database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create application user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    plugin: caching_sha2_password
    plugin_auth_string: "{{ vault_mysql_password }}"
    salt: "1234567890abcdefghij"
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock


- name: Configure MySQL
  ansible.builtin.template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: "0644"
  notify: Restart MySQL
