---
- name: Create application directory
  ansible.builtin.file:
    path: "{{ app_directory }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Copy application
  ansible.builtin.copy:
    src:  "{{ playbook_dir }}/../docker-project/"
    dest: "{{ app_directory }}/"
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Deploy docker compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ app_directory }}/docker-compose.yml"
    owner: ubuntu
    group: ubuntu
    mode: "0600"

- name: Deploy PHP database configuration
  ansible.builtin.template:
    src: config.php.j2
    dest: "{{ app_directory }}/public/config.php"
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Build and start Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ app_directory }}"
    build: always
    state: present
