pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Ansible Syntax Check') {
            steps {
                sh '''
                    ansible-playbook \
                        -i jenkins/ansible/inventory.ini \
                        --syntax-check \
                        jenkins/ansible/cicd/deploy.yml

                    ansible-playbook \
                        -i jenkins/ansible/inventory.ini \
                        --syntax-check \
                        jenkins/ansible/cicd/health-check.yml
                '''
            }
        }

        stage('Ansible Lint') {
            steps {
                sh '''
                    ansible-lint jenkins/ansible/cicd/deploy.yml
                    ansible-lint jenkins/ansible/cicd/health-check.yml
                '''
            }
        }

        stage('Ansible Connectivity Test') {
            steps {
                sshagent(['ansible-ssh-key']) {
                    sh '''
                        ansible \
                            -i jenkins/ansible/inventory.ini \
                            webservers \
                            -m ping
                    '''
                }
            }
        }

        stage('Health Check') {
            steps {
                sshagent(['ansible-ssh-key']) {
                    sh '''
                        ansible-playbook \
                            -i jenkins/ansible/inventory.ini \
                            jenkins/ansible/cicd/health-check.yml
                    '''
                }
            }
        }
    }
}
