---
- name: Configure database
  hosts: databases
  become: true

  roles:
    - database

- name: Configure webservers
  hosts: webservers
  become: true


vars:
    application_source: "{{ playbook_dir }}/../docker-project/"

  roles:
    - docker
    - app
