---
- name: Configure web servers
  hosts: webservers
  become: true

  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all/vault.yml
    - ../group_vars/webservers.yml

  roles:
    - docker
    - app
